# Generated by Django 4.1.4 on 2022-12-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails')),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails')),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
