# Generated by Django 4.2.11 on 2024-04-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_image_alter_file_file_alter_file_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
